Repository balena-os/balena-supervisor, pull requests merged in 2018-03, with the labels that each got.

#565 Update locking docs update, again
  CHANGELOG.md
  docs/update-locking.md
  package.json
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#563 Fix the way commands and entrypoints in string form are parsed
  src/compose/service.coffee
Labels: flow/in-review, procbots/versionbot/no-checks

#568 Convert object to array when normalising legacy target apps
  CHANGELOG.md
  package.json
  src/device-state.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#569 compose: fix volume migration code
  CHANGELOG.md
  package.json
  src/compose/volumes.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#570 lib: add missing flag to openAsync()
  CHANGELOG.md
  package.json
  src/lib/fs-utils.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#571 compose: fix type error, createVolume returns a promise
  CHANGELOG.md
  package.json
  src/compose/volumes.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#574 Fix bug in require for migrations for legacy preload
  CHANGELOG.md
  package.json
  src/device-state.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#575 Fix bug in image management after update
  CHANGELOG.md
  package.json
  src/application-manager.coffee
  src/migrations/20171129064057_multicontainer.js
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#577 gosuper: Treat systemd unit states that are not "inactive" or "deacti…
  CHANGELOG.md
  gosuper/gosuper/api.go
  package.json
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#579 Some fixes for the supervisor API
  CHANGELOG.md
  package.json
  src/application-manager.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#581 When migrating from legacy supervisors, mark the temporary compositio…
  CHANGELOG.md
  package.json
  src/application-manager.coffee
  src/migrations/20171129064057_multicontainer.js
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#584 Fix updates when only releaseId and imageId have changed
  CHANGELOG.md
  package.json
  src/application-manager.coffee
  src/compose/service-manager.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#585 DeviceConfig: avoid trying to enable or disable the VPN when in offline mode
  CHANGELOG.md
  package.json
  src/device-config.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#586 Fix using hostname from host when network mode is host, and fix working_dir comparison
  CHANGELOG.md
  package.json
  src/application-manager.coffee
  src/compose/service.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#588 Fix the check for whether the device is provisioned by correctly get…
  CHANGELOG.md
  package.json
  src/api-binder.coffee
  src/config.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#589 Avoid trying to clean up the supervisor image if it has several tags …
  CHANGELOG.md
  package.json
  src/compose/images.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#572 automation: Use ssh instead of https to PR to meta-resin
  CHANGELOG.md
  automation/pr-to-meta-resin.sh
  package.json
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#593 In /v1/apps/:appId/stop, wait for the service to exit before responding
  CHANGELOG.md
  package.json
  src/application-manager.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#591 Force reboots and shutdowns if lock override is enabled
  CHANGELOG.md
  docs/API.md
  package.json
  src/device-state.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#595 Trim whitespace from the hostname file on the host before passing it …
  CHANGELOG.md
  package.json
  src/application-manager.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#599 Remove any leftover knex migrations locks before running migrations
  CHANGELOG.md
  knexfile.js
  package.json
  src/db.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#605 Handle incorrectly parsed env vars from docker inspect
  CHANGELOG.md
  package.json
  src/lib/conversions.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#596 Back off fetching the target state exponentially, for faster retries …
  CHANGELOG.md
  package.json
  src/api-binder.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#606 Avoid weird cwd errors when dist does not exist with sync
  CHANGELOG.md
  package.json
  sync.js
Labels: flow/in-review

#608 Respond to reboot and shutdown endpoints with a success object
  CHANGELOG.md
  package.json
  src/device-state.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge
