Repository balena-os/balena-supervisor, pull requests merged in 2018-04, with the labels that each got.

#613 Fix falling back to delta from scratch losing auth info.
  CHANGELOG.md
  package.json
  src/docker-utils.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#617 Add mocha to enable unit testing
  .editorconfig
  package.json
  test/compose/service.spec.coffee
Labels: flow/in-review

#616 Fix regex for parsing memory numbers
  .editorconfig
  CHANGELOG.md
  Dockerfile
  package.json
  src/compose/service.coffee
  test/compose/service.spec.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#624 Move to Node 6.13.1.
  CHANGELOG.md
  Dockerfile
  package.json
Labels: procbots/versionbot/ready-to-merge

#602 Add ability to use self-signed CAs passed via `config.json`.
  CHANGELOG.md
  entry.sh
  package.json
Labels: procbots/versionbot/ready-to-merge

#628 Properly propagate delta failure
  CHANGELOG.md
  package.json
  src/lib/docker-utils.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#629 [6.X] Properly propagate delta failure
  CHANGELOG.md
  circle.yml
  package.json
  src/docker-utils.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#625 Do not try attach to containers that aren't running, and clean up dead containers
  CHANGELOG.md
  package.json
  src/application-manager.coffee
  src/compose/service-manager.coffee
  src/compose/service.coffee
  src/lib/log-types.coffee
  tools/dind/Dockerfile
Labels: flow/in-review, procbots/versionbot/ready-to-merge

#637 Remove trailing slashes from working directories of services
  CHANGELOG.md
  package.json
  src/compose/service.coffee
  test/compose/service.spec.coffee
Labels: flow/in-review, procbots/versionbot/ready-to-merge
